


spring:
  datasource:
    url: jdbc:mysql://121.36.160.23:3306/spring_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: mysql123
#  security:
#    user:
#      name: luke
#      password: 123
#      roles: admin
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
